### ISSUE TITLE
install

### ISSUE THREAD

**Issue by MarkRause** [orbingol/NURBS-Python#149]
Hi I'm getting this error trying to install on Spyder  4.25  any ideas?? thanks in advance

conda install -c orbingol geomdl
Traceback (most recent call last):

  File "<ipython-input-3-ce1a9752d7ef>", line 1, in <module>
    get_ipython().run_line_magic('conda', 'install -c orbingol geomdl')

  File "C:\Spydersucks\pkgs\IPython\core\interactiveshell.py", line 2344, in run_line_magic
    result = fn(*args, **kwargs)

  File "<decorator-gen-101>", line 2, in conda

  File "C:\Spydersucks\pkgs\IPython\core\magic.py", line 187, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)

  File "C:\Spydersucks\pkgs\IPython\core\magics\packaging.py", line 79, in conda
    raise ValueError("The python kernel does not appear to be a conda environment.  "

ValueError: The python kernel does not appear to be a conda environment.  Please use ``%pip install`` instead.

**Comment by orbingol** [comment]
I've received the same message by email and responded in detail. I don't think this is a geomdl issue. I am closing this one.
